// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

/**
 * @title GaslessCartPaymaster
 * @dev Reimburses gas fees by pulling stablecoins directly from users based on signed intents.
 */
contract GaslessCartPaymaster {
    using ECDSA for bytes32;

    address public owner;
    IERC20 public stablecoin;
    address public verifyingSigner;

    // Security tracking mapping to prevent users from reusing signatures (Replay Attacks)
    mapping(address => uint256) public nonces;

    event PaymentProcessed(
        address indexed user,
        address indexed merchant,
        uint256 amount,
        uint256 executionFee
    );

    modifier onlyOwner() {
        require(msg.sender == owner, "Not contract owner");
        _;
    }

    constructor(address _stablecoin, address _verifyingSigner) {
        owner = msg.sender;
        stablecoin = IERC20(_stablecoin);
        verifyingSigner = _verifyingSigner;
    }

    /**
     * @notice Executes a merchant purchase on behalf of a user using an off-chain signature.
     * @param user The address of the shopper purchasing the item.
     * @param merchant The target business wallet receiving the stablecoins.
     * @param amount The cost of the product in stablecoin units.
     * @param executionFee The gas reimbursement fee paid to this paymaster contract.
     * @param signature The cryptographic proof vector generated by the user's private key.
     */
    function executeGaslessPurchase(
        address user,
        address merchant,
        uint256 amount,
        uint256 executionFee,
        bytes calldata signature
    ) external {
        // 1. Recreate the cryptographic hash that the user signed off-chain
        bytes32 messageHash = keccak256(
            abi.encodePacked(
                user,
                merchant,
                amount,
                executionFee,
                nonces[user],
                block.chainid
            )
        );

        // 2. Format the hash into an Ethereum Signed Message standard
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(
            messageHash
        );

        // 3. Extract the signer identity from the signature payload
        address signer = ethSignedMessageHash.recover(signature);

        // 4. Assert that the signature matches our trusted backend validator
        require(signer == verifyingSigner, "Invalid cryptographic signature");

        // 5. Increment user nonce immediately to neutralize replay exploits
        nonces[user]++;

        // 6. Transfer the product cost to the merchant
        require(
            stablecoin.transferFrom(user, merchant, amount),
            "Merchant settlement failed"
        );

        // 7. Transfer the gas reimbursement fee to this contract
        require(
            stablecoin.transferFrom(user, address(this), executionFee),
            "Gas reimbursement failed"
        );

        emit PaymentProcessed(user, merchant, amount, executionFee);
    }

    // Allows owner to withdraw collected stablecoin reimbursements
    function withdrawTokens() external onlyOwner {
        uint256 balance = stablecoin.balanceOf(address(this));
        stablecoin.transfer(owner, balance);
    }
}
